# -*- coding: utf-8 -*-
"""ASSINEMENT 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzZmt8o05CAZgB7S-3gTX_l8VgxyG6or
"""

#QUESTION 1
a="saurabh kumar"
b=[4,6,9,2]
c=4.66
d=(6,8,2,7,'str')
#question 2
a=str
b=str
c=list
d=int

#Question 3
#divide
print(6/3)
#modulus
a = 10
b = 3
remainder = a % b
print(remainder)  # Output: 1
# (Floor Division Operator):
a = 10
b = 3
result = a // b
print(result)  # Output: 3
#Exponentiation Operaton
a = 2
b = 3
result = a ** b
print(result)  # Output: 8

#question 4
l=[2,5,7,'saurabh',5+6j,4.66,True,'kumar',False,6]
for i in l:
  print(i,type(i))

#question 5
A = int(input("Enter a number A: "))
B = int(input("Enter a number B: "))
count = 0
while A % B == 0:
    A /= B
    count += 1
if count > 0:
    print("Number of times A is divisible by B:", count)
else:
    print("A is not purely divisible by B")

#question 6
data_list = [i for i in range(1, 26)]
for num in data_list:
    if num % 3 == 0:
        print(f"{num} is divisible by 3")
    else:
        print(f"{num} is not divisible by 3")

#Question 7
a='saurabh'
a[2]=s# imutable
l=[4,7,8,9]
l[1]=10 #mutable